# Generated by Django 2.1.7 on 2019-07-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('slug', models.SlugField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
