# Generated by Django 2.1.7 on 2019-03-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='top_name',
            field=models.CharField(max_length=264, unique=True),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='name',
            field=models.CharField(max_length=264, unique=True),
        ),
    ]
