# Generated by Django 2.1.7 on 2019-03-27 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20190327_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='first_app.Topic'),
            preserve_default=False,
        ),
    ]
