# Generated by Django 2.1.7 on 2019-03-27 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_webpage_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrecord',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='first_app.Webpage'),
            preserve_default=False,
        ),
    ]
